### ISSUE TITLE
Removing different subdirectory prefixes for all TARs in a folder?

### ISSUE THREAD

**Issue by frankang** [mxmlnkn/ratarmount#107]
Hello~ First, I would like to express my appreciation for the usefulness of this repository. It saved me a lot of time and effort in working with TAR files.

I have a folder that contains multiple TAR files, each with a different subdirectory prefix (e.g. path1, path2, etc.). I would like to mount this folder using ratarmount, but I want to strip out the subdirectory prefix (`path1/, path2/, ...` ) for all of them. Is there a way to achieve this? My TAR folder looks like this:
```
tar_file1.tar
   - path1/1-file1
   - path1/1-file2
   - path1/1-file3
   - ...

tar_file2.tar
   - path2/2-file1
   - path2/2-file2
   - path2/2-file3
   - ...
```

Any help would be greatly appreciated. Thank you again for this amazing tool!

**Comment by mxmlnkn** [comment]
I do have a hacky solution:

```bash
# Generate test case
mkdir foo1
mkdir foo2
echo a > foo1/a
echo b > foo1/b
echo c > foo2/c
echo d > foo2/d
tar cf foo1.tar foo1
tar cf foo2.tar foo2

# Use (deprecated) --prefix or -o subdir... to get rid of the prefix for each archive
ratarmount -o modules=subdir,subdir=foo1 foo1.tar mounted-foo1
ratarmount -o modules=subdir,subdir=foo2 foo2.tar mounted-foo2

# Unite both mounts
ratarmount mounted-foo1 mounted-foo2 mounted

# Check results
tree mounted
```

Output:

```
mounted
├── a
├── b
├── c
└── d

0 directories, 4 files
```

I guess in general it could be nice to generalize the `--transform-recursive-mount-point` into a generic `--transform-paths` option.

**Comment by frankang** [comment]
Thank you. The above workaround works, however there is a noticeable latency increase (at lease 5X) when opening the files in the final "merged" mountpoint. The CPU usage of the ratarmount process is very high during the wait time.

**Comment by mxmlnkn** [comment]
Are the 100k files all in the top-level? One problem with union mount is that it has to find out to which archive a requested file belongs to. A cache exists to deal with this case but it has some thresholds. If the cache cannot be used, then on each file access, it has to check all union-mounted archives (or folders) whether it has the requested file. Because of this, the lookup time increases with the number of union mount sources.

Is there any output regarding the cache when calling `ratarmount -d 3 -f mounted-foo1 mounted-foo2 mounted` with `-d 3`?

**Comment by frankang** [comment]
Yes, they are all in the top-level.

**Comment by mxmlnkn** [comment]
Unfortunately not (yet). I have attached an AppImage of the current development version that has these command line options:

```
  --union-mount-cache-max-depth UNION_MOUNT_CACHE_MAX_DEPTH
                        Maximum number of folder levels to descend for building the union mount cache. (default: 1024)
  --union-mount-cache-max-entries UNION_MOUNT_CACHE_MAX_ENTRIES
                        Maximum number of paths before stopping to descend into subfolders when building the union mount cache. (default: 100000)
  --union-mount-cache-timeout UNION_MOUNT_CACHE_TIMEOUT
                        Timeout before stopping to build the union mount cache. (default: 60)
```

Try it with something like `ratarmount.AppImage --union-mount-cache-timeout 3600 --union-mount-cache-max-entries 10000000 ...` (10 million files maximum, and maximum 1h). 

[ratarmount-manylinux2014_x86_64.AppImage.zip](https://github.com/mxmlnkn/ratarmount/files/10833884/ratarmount-manylinux2014_x86_64.AppImage.zip)

**Comment by frankang** [comment]
Running the AppImage gives the error below:
`fusermount: mount failed: Operation not permitted
[Error] FUSE mountpoint could not be created. See previous output for more information.`
Whatever, I will try the develop branch later and see if it works. Thanks.

**Comment by mxmlnkn** [comment]
Weird... For the development branch, try:

```bash
python3 -m pip install --user --force-reinstall \
    'git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmountcore&subdirectory=core' \
    'git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmount'
```

**Comment by frankang** [comment]
Looks like the `isImmutable` property in the FolderMountSource.py file is always false for a `FolderMountSource` object, causing an empty `folderCache` in the UnionMount process.

https://github.com/mxmlnkn/ratarmount/blob/e61800c4d2ddedc46a2937fce2701ec3039788e5/core/ratarmountcore/FolderMountSource.py#L54-L58

https://github.com/mxmlnkn/ratarmount/blob/4ef96f038bf1096c5b9441c4d00e6a43964efbde/core/ratarmountcore/UnionMountSource.py#L55-L57

**Comment by mxmlnkn** [comment]
Ah, I didn't think of that. But then why was there a timeout in your output :/. It shouldn't even start to build the cache then. It should also be possible to detect folders residing on read-only filesystems and flag those as immutable. It might even be possible to use something like inotify to detect file creations and deletions inside the folders so that the cache can be updated accordingly. With that the immutability check wouldn't be necessary anymore.

**Comment by frankang** [comment]
Does the “/” sign in `self.folderCache = {"/": [m for m in self.mountSources if m.isImmutable()]} ` mean an operation after timeout? 
https://github.com/mxmlnkn/ratarmount/blob/4ef96f038bf1096c5b9441c4d00e6a43964efbde/core/ratarmountcore/UnionMountSource.py#L55-L57
I also tried setting the isImmutable() to be always `True` in the foldermountsource.py file, then it does require more time to build the cache, but the file access latency only decreased marginally.

**Comment by mxmlnkn** [comment]
I want to create some benchmarks to look into it in depth. I need some further information about your setup:

 - How many files are there per tar archive? 
 - How large are the files on average?
 - How many tar archives are you trying to union mount?
 - What exactly are you measuring? `time cat file-path`? `time head -c 1 file-path`?

**Comment by mxmlnkn** [comment]
I've pushed a quick implementation of a `--transform` option to the develop branch. This option is only applied during index creation, so you should use it with `-c` or remove the index before.

Create test archives:

```bash
mkdir folder1
mkdir folder2
echo hi > folder1/a
echo there > folder2/b
tar cf folder1.tar folder1
tar cf folder2.tar folder2
```

Use like this to remove the top-level folder:

```console
> ratarmount -c folder1.tar folder2.tar mountpoint
> tree mountpoint

mountpoint
├── folder1
│   └── a
└── folder2
    └── b

2 directories, 2 files

> ratarmount -u mountpoint
> ratarmount -d 3 -c --transform '^/[^/]*/' '' folder1.tar folder2.tar mountpoint
> tree mountpoint

mountpoint
├── a
└── b

0 directories, 2 files
```

I have not tested the performance of this yet and there is still much to do to implement this correctly and consistently in ratarmount. Currently, it only works for TAR archives.

**Comment by frankang** [comment]
Oops, sorry for my late reply, will test the `--transform` option ASAP. Thanks again for the quick fix!

**Comment by frankang** [comment]
Tried the `--transform` option last week and tested it for a few days, I think it did solve the problem. Thank you for the solution!

**Comment by mxmlnkn** [comment]
You solved your question yourself, but as there is more demand, I'll take that as a cue to finish that feature with higher priority. The commit message also lists the open issues that I want to fix before merging it. I guess I could also live without it working for RAR files if I don't find time to implement this feature there.
