### ISSUE TITLE
Option to read from stdin

### ISSUE THREAD

**Issue by cmcclen** [mxmlnkn/ratarmount#122]
I do not see an option to allow ratarmount to use stdin as a source. Is that possible?

**Comment by mxmlnkn** [comment]
No. What should it do? Buffer the whole input from stdin into RAM and then expose it as a FUSE mount? That should be doable to implement.

**Comment by mxmlnkn** [comment]
I'm not seeing the use case right now. I will reopen this if there is more explanation or more requests.
