### ISSUE TITLE
Add 7z support

### ISSUE THREAD

**Issue by detain** [mxmlnkn/ratarmount#123]
https://github.com/andrew-grechkin/fuse3-p7zip
this provides a 'fuse3-p7zip' binary that mounts 7z files via fuse3.   Is there any way of incorporating support for this into ratarmount?

**Comment by mxmlnkn** [comment]
fuse3-p7zip is a C++ project. I guess it could be possible to refactor it into a library and use it but it wouldn't feel right and the license also is incompatible with ratarmount.

The problem with 7z support right now is that there are no sufficiently usable Python modules I can use for that. There are multiple libarchive wrappers but they all have their own problems. There are also some 7zip wrappers but I didn't look deeply into those, yet. I think some of them did the rarfile module way and basically just look for the 7z tool binaries and call that, which is not very performant or clean.

I'd also like to have 7z support #109 . PRs are welcome.

**Comment by mxmlnkn** [comment]
@detain I'm finished with the libarchive backend in #130 , which also supports 7z. If you want to test it out, I'd welcome feedback. That branch can be installed directly from git with:

```
python3 -m pip install --user --force-reinstall \
    'git+https://github.com/mxmlnkn/ratarmount.git@libarchive#egginfo=ratarmountcore&subdirectory=core' \
    'git+https://github.com/mxmlnkn/ratarmount.git@libarchive#egginfo=ratarmount'
```

There are some inherent performance problems with libarchive, but I tried to avoid the bigger pitfalls that e.g. archivemount suffers from.
