### ISSUE TITLE
Mount suceeded but nothing is shown

### ISSUE THREAD

**Issue by glyh** [mxmlnkn/ratarmount#129]
I tried to mount rar and zip in home, and I got a `fusermount: mounting over filesystem type 0xca451a4e is forbidden` error. Then I move the files to /tmp and mount them, I succeeded this time but when I look into the folder nothing is inside.

**Comment by mxmlnkn** [comment]
I have no idea about the "forbidden" error message. It must be related to how FUSE is configured on your system and on what file system you are trying to mount it. Mounting inside `/tmp` seems like a good workaround.

If nothing is shown inside the folder, then there might have been an error. Please try running ratarmount with `ratarmount -f -d 3` to show debugging output.

(If there are no error messages, and I doubt it, then it might be a problem with FUSE. To diagnose that, you could try to use ratarmount as a library:
```bash
python3 -c 'import ratarmountcore as rmc; a = rmc.open( "archive.zip" ); print(a.listDir("/"))'
```
