### ISSUE TITLE
Input/output error on remove not empty dir

### ISSUE THREAD

**Issue by r3t4k3r** [mxmlnkn/ratarmount#134]
Bug while removing not empty folder

![image](https://github.com/mxmlnkn/ratarmount/assets/86055096/e7f2987b-474c-4ed0-b24c-dcab713c0a99)

**Comment by mxmlnkn** [comment]
I have trouble reproducing this. The traceback itself stems from the code logic that tries to remove the folder inside the overlay folder while it is not empty. The existence of this folder inside the overlay folder irritates me. It will only be created if e.g. a file was created in the mount point. Did you create some files while it was mounted? What folders are actually in the overlay folder, e.g., with `tree nonroot.overlay`?

What I tried without being able to reproduce the problem:
 - Mounting and deleting everything in a TAR of my firefox profile.
 - Creating a TAR with files and folders with read-only permissions.
 - Creating a file in the mountpoint subfolder and then delete everything.
 - Removing the write permissions of the newly created file in the mountpoint subfolder.
