### ISSUE TITLE
bad index on tars created with file lists

### ISSUE THREAD

**Issue by al-zatv** [mxmlnkn/ratarmount#2]
I can create archives by specifying list of files to include in tar file. ratarmount can't work on such tars.

Steps to reproduce problem are below. Archive with problematic files,tars,pickles is attached.

[reproduce-bug-tar-list.tar.gz](https://github.com/mxmlnkn/ratarmount/files/3169498/reproduce-bug-tar-list.tar.gz)
`
#### Creating tar with and without list of files to include
xx/root$ echo -n "dir_1/dir_1_1/file_1_1_0.txt" > ../file-list.txt

xx/root$ tar cvf ../tar-list.tar -T ../file-list.txt
dir_1/dir_1_1/file_1_1_0.txt

xx/root$ tar cvf ../tar-no-list.tar *
dir_1/
dir_1/dir_1_1/
dir_1/dir_1_1/file_1_1_0.txt

#### ratarmounting
xx/root$ cd ..

xx$./ratarmount.py tar-list.tar 
Creating offset dictionary for tar-list.tar ...
Creating offset dictionary for tar-list.tar took 0.00s

xx$ ./ratarmount.py tar-no-list.tar 
Creating offset dictionary for tar-no-list.tar ...
Creating offset dictionary for tar-no-list.tar took 0.00s

#### it is OK:
xx$ cd tar-no-list/
xx/tar-no-list$ ls -l
total 4
dr-xr-xr-x 2 zatv zatv 10240 май 12 00:03 ./
drwxrwxr-x 5 zatv zatv  4096 май 12 00:05 ../
dr-xr-xr-x 2 zatv zatv     0 май 11 23:56 dir_1/

#### it is BUG:
xx$ cd ..
xx$ cd tar-list/
xx/tar-list$ ls -l
ls: cannot access 'dir_1': Read-only file system
total 4
dr-xr-xr-x 2 zatv zatv 10240 май 12 00:04 ./
drwxrwxr-x 5 zatv zatv  4096 май 12 00:05 ../
?????????? ? ?    ?        ?            ? dir_1

xx/tar-list$ cd dir_1
bash: cd: dir_1: Read-only file system
`

**Comment by al-zatv** [comment]
btw, output from debug mode (for other tar, not mentioned earlier)

[getattr( path = / , fh = None )]
[getattr( path = / , fh = None )]
[readdir( path = / , fh = 0 )] getFileInfo.keys: dict_keys(['MyFolder'])
[getattr( path = /MyFolder , fh = None )]
Could not find path: /MyFolder
[getattr( path = / , fh = None )]
[getattr( path = /MyFolder , fh = None )]
Could not find path: /MyFolder
[getattr( path = / , fh = None )]
[getattr( path = / , fh = None )]

**Comment by mxmlnkn** [comment]
Thank you for your extensive and helpful bug report!

The problem is a rather easy one. I assumed that all parent folders of files are first mentioned in the TAR with corresponding metainformation. When specifying a file directly, this is not the case. 

This means that FUSE can't get metainformation for those parent folders but the file is still shown as being in such an unknown and therefore unreadable directory. The fix now creates such parent folders with some default information.

**Comment by al-zatv** [comment]
Looks like my problem solved. Thank you for your fix!
