### ISSUE TITLE
Write support

### ISSUE THREAD

**Issue by mxmlnkn** [mxmlnkn/ratarmount#22]
See [this](https://github.com/mxmlnkn/ratarmount/issues/21#issuecomment-576021064) comment.

At least for uncompressed TAR archives, I could easily add write support for now. Although because of the mentioned performance pit traps, it should be by default but it should only be triggered with another command line option. I think archivemount also has write support, so whether to add this to ratarmount is kinda questionable and if done so it should definitely work with very large tars for which archivemount has problems.

**Comment by cardoso-neto** [comment]
I have a use case for this. 
I'm currently trying to use ratarmount for one of my backup workflows and being able to append to an uncompressed .tar file would be useful.
Whenever I do this from my python scripts, I get a nasty `Exception: ('TAR file for this SQLite index has changed size from, x, 'to', y)` and it rebuilds the whole index.
Maybe ratar could do a quick check on the last file offset it knows of (just to make sure it's dealing with the same tar) and then build the index from that point onward.
If it's somehow easier to just enable writing through the fusemount, I would also love that.

**Comment by mxmlnkn** [comment]
@cardoso-neto I think, you misunderstood the original issue as there are many layers of "write support".

The general layers of write support, I see:

 - Detect when TAR archives only grew and avoid rebuilding the index from scratch, see #78
 - Make the mount point writable, e.g., with a write overlay
 - Not only make the mount point writable but also write back those modifications to the original TAR archive

The last one is what I had in mind for this issue. And it is this and the write overlay which I implemented in the develop branch. It can already be tested out by installing from the develop branch like so:

```bash
python3 -m pip install --user --force-reinstall 'git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmountcore&subdirectory=core'
python3 -m pip install --user --force-reinstall git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmount
```

or by installing the as of yet unreleased (temporary) AppImage:

```bash
wget -O ratarmount https://github.com/mxmlnkn/ratarmount/blob/2531102c5c0c1765f59b0d46e9a70553abfaea8e/AppImage/ratarmount-manylinux2014_x86_64.AppImage?raw=true
chmod u+x ratarmount

# Test example, building from source inside the mounted folder
wget 'https://github.com/Kitware/CMake/releases/download/v3.23.0-rc3/cmake-3.23.0-rc3.tar.gz'
gzip -d cmake-3.23.0-rc3.tar.gz

./ratarmount --write-overlay overlay cmake-3.23.0-rc3.tar cmake
cd cmake/cmake-3.23.0-rc3
./configure  # This takes a long time even without ratarmount, you can simply cancel it after a while
cd -

find overlay -maxdepth 2 -print

ratarmount -u cmake  # unmount alternative to fusermount

./ratarmount --commit-overlay --write-overlay overlay cmake-3.23.0-rc3.tar
```

The write overlay folder acts as a temporary buffer before writing all modifications back to the archive in one go on user command (`--commit-overlay`). The latter is not fully finished yet, it will only print out the TAR commands to effect the desired archive change, it will not execute them automatically (yet).

After further testing and merging that into master, I'll close this issue.

**Comment by cardoso-neto** [comment]
I shall test it out today.

**Comment by cardoso-neto** [comment]
I haven't had the time to test it out, but it's on my radar still.
For your curiosity's sake, the tool I was writing is an extension to git-annex, which would store data inside .tars to ease moving data around (thinking about the use case of many small files, e.g., pics or logs).

**Comment by mxmlnkn** [comment]
> I haven't had the time to test it out, but it's on my todo still. For your curiosity's sake, the tool I was writing is an extension to git-annex, which would store data inside .tars to ease moving data around (thinking about the use case of many small files, e.g., pics or logs).

I love to know about use cases. Personally, I also use it for lot of write-once-read-many data because I don't want millions of small files on my raw file system because it still has many disadvantages especially slow copy times :/. What data sizes and file counts are we talking about in your case?

I just now pushed some commits to detect whether a TAR only grew. I didn't update the AppImage because it is cumbersome to distribute, you would have to install via pip git. 

Now you should be able to do things like:

```bash
head -c $(( 256 * 1024 * 1024 )) /dev/urandom > random-256MiB.dat
tar --create --file large.tar random-256MiB.dat
timeout 1s ratarmount -f large.tar
    # Creating offset dictionary for large.tar ...
    # Creating new SQLite index database at large.tar.index.sqlite
    # Creating offset dictionary for large.tar took 0.00s
    # Writing out TAR index to large.tar.index.sqlite took 0s and is sized 24576 B
echo foo > bar
tar --append --file large.tar bar
timeout 1s ratarmount -f large.tar
    # Successfully loaded offset dictionary from large.tar.index.sqlite
    # Detected TAR being appended to. Will only analyze the newly added 0.000 % of data.
    # Creating offset dictionary for large.tar ...
    # Creating offset dictionary for large.tar took 0.00s
head -c $(( 2 * 1024 * 1024 )) /dev/urandom > bar2
tar --append --file large.tar bar2
timeout 1s ratarmount -f large.tar
    # Successfully loaded offset dictionary from large.tar.index.sqlite
    # Detected TAR being appended to. Will only analyze the newly added 0.008 % of data.
    # Creating offset dictionary for large.tar ...
    # Creating offset dictionary for large.tar took 0.00s
```

The detection for appended archives is already pretty strict but it might become even stricter in the future. The underlying problem is that verifying exactly that the archive only grow would be as much if not more expensive than creating the index from scratch. Therefore, only a random selection of ~4k files are checked. This also means that archives with less than 4k files should simply always be created from scratch when they change. In the above examples it is not yet the case because the heuristic currently looks at the archive size not the number of files in the archive. I'll change that soon.

Instances where it will create from scratch even if the archive might only have been appended to:
 - The last file in the archive is a sparse file
 - The archive is compressed
 - The archive is less than 64 MiB (will change to: contains roughly equal or less than the number of files we would validate anyway)
 - The archive did not grow significantly. (If the archive quadrupled in size, then the overhead of analyzing the first quarter would be negligible in contrast to the added parts we have to analyze anyway assuming a similar average file size)

**Comment by nathanweeks** [comment]
I tried the new `--write-overlay` option in ratarmount 0.11.0 on a CentOS 7 host; when I subsequently attempted to use the `--commit-overlay` option, the following error occurred:

```
$ ratarmount --write-overlay /tmp/overlay --commit-overlay code-server-4.1.0-linux-amd64.tar 
To commit the overlay folder to the archive, these commands have to be executed:

    tar --delete --null --verbatim-files-from --files-from='/tmp/tmpdcv756i9/deletions.lst' \
        --file 'code-server-4.1.0-linux-amd64.tar' 2>&1 |
       sed '/^tar: Exiting with failure/d; /^tar.*Not found in archive/d'
    tar --append -C '/tmp/overlay' --null --verbatim-files-from --files-from='/tmp/tmpdcv756i9/append.lst' --file 'code-server-4.1.0-linux-amd64.tar'

Committing is an experimental feature!
Please confirm by entering "commit". Any other input will cancel.
> commit
tar: unrecognized option '--verbatim-files-from'
Try `tar --help' or `tar --usage' for more information.
[Error] There were problems when trying to delete files.
```

Apparently the`--verbatim-files-from` option was introduced in GNU tar 1.29 (https://www.gnu.org/software/tar/), whereas CentOS 7 bundles GNU tar 1.26. It might be worth mentioning this requiremet in the README, as CentOS 7 will continue to be used on enterprise hosts and HPC clusters until it's EOL'ed in mid 2024.

**Comment by mxmlnkn** [comment]
@nathanweeks

[It seems](https://www.gnu.org/software/tar/manual/html_node/nul.html#nul) that `--null` already implies a behavior similar to `--verbatim-files-from`. So the fix is easy, simply remove the command line option.

> In tar, ‘--null’ also disables special handling for file names that begin with dash (similar to ‘--verbatim-files-from’ option).

You can try it out with:

```bash
python3 -m pip install --user --force-reinstall git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmount
```

**Comment by mxmlnkn** [comment]
I'll close this issue for now because it has been implemented in 0.11.0. But, feel free to give feedback here or open a separate issue if you have problems or further suggestions.

**Comment by mxmlnkn** [comment]
@nathanweeks One last thing, did you use the AppImage? Now that I'm depending on GNU tar, I could have bundled it with the AppImage for maximum compatibility.

**Comment by nathanweeks** [comment]
@mxmlnkn I did not use the AppImage (nor had I used an AppImage previously), but I just tried it on the local HPC cluster, and it seems that if `tar` were available in the AppImage, then the AppImage executable could be conveniently made available to users via [lmod](https://lmod.readthedocs.io/en/latest/).

Once the OS on our cluster is updated to another OS (sometime next year) the tar version won't be an issue for us, so please prioritize as you see fit.

I'll add that AppImage looks quite neat!

**Comment by mxmlnkn** [comment]
@nathanweeks I noticed that ironically manylinux2014 also runs on CentOS 7. So, adding tar to the AppImage gets just a bit more complicated again as I would have to build from source. But tar should be installed even on most minimal systems and I already have found that `--verbatim-from-file` was redundant anyway. So, I'll just leave the AppImage as is and release a 0.11.1 version, which will simply omit the `--verbatim-from-file` option, maybe this weekend or the next.
