### ISSUE TITLE
Add support for hardlink-ed files in .tar?

### ISSUE THREAD

**Issue by soichih** [mxmlnkn/ratarmount#28]
I was troubleshooting some issue, and I have discovered that some .tar files contain hard-links. I didn't know tar could support hard links, but we have a lot of these that we need to handle..

Here is the example tar file.
> http://dev1.soichi.us/tmp/5b525b1258153f004fc0883f.tar

This contains fils like `./output/surf/rh.white.K` which is a hardlink to `./output/surf/rh.white.preaparc.K`

Following files are also hard links

```
./output/surf/lh.white.K
./output/surf/lh.white.preaparc.H
./output/surf/rh.white.preaparc.K
./output/surf/rh.white.preaparc.H
```

When I try to mount this .tar with ratarmount, these files shows up with `Input/output error` and I can not access them.

```
hayashis@haswell:~/test/ratarmount/5b525b1258153f004fc0883f/output/surf $ ls -lrt
ls: cannot access 'lh.white.K': Input/output error
ls: cannot access 'lh.white.preaparc.H': Input/output error
ls: cannot access 'rh.white.preaparc.H': Input/output error
ls: cannot access 'rh.white.preaparc.K': Input/output error
total 0
?????????? ? ?        ?              ?            ? rh.white.preaparc.K
?????????? ? ?        ?              ?            ? rh.white.preaparc.H
?????????? ? ?        ?              ?            ? lh.white.preaparc.H
?????????? ? ?        ?              ?            ? lh.white.K
-r--r--r-- 2 hayashis hayashis 5165534 Jul 20  2018 lh.orig.nofix
-r--r--r-- 2 hayashis hayashis 5028590 Jul 20  2018 rh.orig.nofix
-r--r--r-- 2 hayashis hayashis 5028984 Jul 20  2018 rh.smoothwm.nofix
-r--r--r-- 2 hayashis hayashis 5165928 Jul 20  2018 lh.smoothwm.nofix
-r--r--r-- 2 hayashis hayashis 5029382 Jul 20  2018 rh.inflated.nofix
-r--r--r-- 2 hayashis hayashis 5166326 Jul 20  2018 lh.inflated.nofix
-r--r--r-- 2 hayashis hayashis 5029777 Jul 20  2018 rh.qsphere.nofix
-r--r--r-- 2 hayashis hayashis 5166721 Jul 20  2018 lh.qsphere.nofix
-r--r--r-- 2 hayashis hayashis  558255 Jul 20  2018 rh.defect_labels
...
```

Is it possible for add support for hardlinks? Or is there a workaround? Recreating all the .tar file with --hard-dereference flag is extremely difficult to do, due to the number of .tar files we have.

**Comment by mxmlnkn** [comment]
The Input/Output error was caused by the returned file mode which flags it as a non-regular, non-directory, non-anything file. I now try to detect this and simply forward the link recursively. I pushed it on develop, You might be able to install it with `pip install git+https://github.com/mxmlnkn/ratarmount.git@develop#egginfo=ratarmount`

**Comment by soichih** [comment]
I've installed the dev version, and I can confirm that it works!

```
hayashis@xps13:~/test/ratarmount/5b525b1258153f004fc0883f/output/surf $ ls -lai
total 0
 7 dr-xr-xr-x 2 hayashis hayashis       0 Jul 20  2018 .
 2 dr-xr-xr-x 2 root     root           0 Jul 20  2018 ..
...
46 -r--r--r-- 2 hayashis hayashis  559019 Jul 20  2018 lh.white.H
47 -r--r--r-- 2 hayashis hayashis  559019 Jul 20  2018 lh.white.K
48 -r--r--r-- 2 hayashis hayashis 5032366 Jul 20  2018 lh.white.preaparc
49 -r--r--r-- 2 hayashis hayashis  559019 Jul 20  2018 lh.white.preaparc.H
50 -r--r--r-- 2 hayashis hayashis  559019 Jul 20  2018 lh.white.preaparc.K
```

Thank you so much for fixing this so quickly!
