### ISSUE TITLE
--recreate-index should be run automatically when archive checksum changes

### ISSUE THREAD

**Issue by rngadam** [mxmlnkn/ratarmount#29]
Had some really annoying behavior with ratarmount where the "view" of the filesystem was completely out of sync with the real tar data (that was replaced with other data at the same path after initial run).

workaround was to run with ```--recreate-index```.

I would suggest keeping a shasum on the tar archive and automatically recreating the index anytime that shasum changes.

**Comment by mxmlnkn** [comment]
I already have something "like" that in 4baba4dbf82b29a48d502f28870ef3e9bfaea3d9 in the develop branch. It stores the TAR file size. Would that be enough? Personally, I'm not really keen to do a checksum for possibly gigabytes of data before each mount, even the index creation would be faster in that case.

**Comment by rngadam** [comment]
@mxmlnkn you're probably right! sounds good.

It would definitely had caught our case.

even safer with the modification timestamp.
