### ISSUE TITLE
Invalid file format

### ISSUE THREAD

**Issue by jose1711** [mxmlnkn/ratarmount#6]
This is what I am getting from `ratarmount`:
```
python ./ratarmount.py /home/jose/.cache/yay/vfs495-daemon/sp84530.tar
Loading offset dictionary from /home/jose/.cache/yay/vfs495-daemon/sp84530.tar.index.custom ...
Traceback (most recent call last):
  File "./ratarmount.py", line 701, in <module>
    serializationBackend = args.serialization_backend  ),
  File "./ratarmount.py", line 555, in __init__
    serializationBackend = serializationBackend )
  File "./ratarmount.py", line 99, in __init__
    self.loadIndex( indexPathWitExt )
  File "./ratarmount.py", line 507, in loadIndex
    self.fileIndex = IndexedTar.load( indexFile )
  File "./ratarmount.py", line 206, in load
    value = IndexedTar.load( file )
  File "./ratarmount.py", line 211, in load
    str( int.from_bytes( valueType, byteorder = 'little' ) ) + ')' )
Exception: Custom TAR index loader: invalid file format (expected msgpack or dict but got0)
```
Tar file looks to be pretty normal:
```
$ tar tvf /home/jose/.cache/yay/vfs495-daemon/sp84530.tar               
drwxrwxrwx 0/0               0 2018-01-05 09:26 SP84530/
-rwxrwxrwx 0/0         2962461 2017-12-29 14:25 SP84530/Validity-Sensor-Setup-4.5-136.0.x86_64.rpm
$ file /home/jose/.cache/yay/vfs495-daemon/sp84530.tar
/home/jose/.cache/yay/vfs495-daemon/sp84530.tar: POSIX tar archive
```

**Comment by mxmlnkn** [comment]
The TAR file does not seem to be the problem. The problem is the created index it tries to load. Could it be that `/home/jose/.cache/yay/vfs495-daemon/sp84530.tar.index.custom` is 0 byte large? Try deleting it. Or calling ratarmount once with the `-c` option and then retry.

**Comment by jose1711** [comment]
Thank you, the `-c` option worked. Would it be possible to catch the exception and provide more human-readable description? With maybe the hint how to fix it?

**Comment by mxmlnkn** [comment]
Yes, it is and I think I will do it. But `-c` recreates the index from scratch, which can be very time-costly and the index should not be in an invalid state in the first place.

Could you try now whether it works without `-c`? I.e., if the newly created index is valid, now?

**Comment by jose1711** [comment]
Yes it works now without `-c` flag too. I remembered how I got into the situation.

- ran `ratarmount` w/o having `msgpack` installed (seeing it as an optional dependency)
- got error but not noticing that a 22B file has been created (`/home/jose/.cache/yay/vfs495-daemon/sp84530.tar.index.custom`)
- installed `msgpack`
- retried - got the `Invalid file format` error

**Comment by mxmlnkn** [comment]
Ok, thank you for the description! I guess trying to run while forgetting to install the dependencies might happen more frequently and I should harden the script against this.
