### ISSUE TITLE
Doesn't work with libfuse 3-3.10.1 due to use of "nonempty" option

### ISSUE THREAD

**Issue by epicfaace** [mxmlnkn/ratarmount#61]
See CI builds for #58 -- we get the following error:

```
ratarmount.stderr.log-  File "/home/runner/work/ratarmount/ratarmount/ratarmount.py", line 2411, in <module>
ratarmount.stderr.log-    cli(sys.argv[1:])
ratarmount.stderr.log-  File "/home/runner/work/ratarmount/ratarmount/ratarmount.py", line 2399, in cli
ratarmount.stderr.log-    fuse.FUSE(
ratarmount.stderr.log-  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/fuse.py", line 711, in __init__
ratarmount.stderr.log:    raise RuntimeError(err)
ratarmount.stderr.log:RuntimeError: 1
runAndCheckRatarmount:145 <- checkUnionMount main
Found warnings while executing: python3 -u /home/runner/work/ratarmount/ratarmount/ratarmount.py -c hardlink hardlink
TEST FAILED!
ratarmount.stdout.log:
ratarmount.stderr.log:
fusermount: unknown option 'nonempty'
```

According to https://github.com/rclone/rclone/issues/3562#issuecomment-533813927, we might just be able to omit the "nonempty" option and it should use that behavior by default.

Additionally, according to https://github.com/rclone/rclone/issues/3562#issuecomment-786679855, the "nonempty" option is accepted and ignored in libfuse 3.10.2+, so this issue really only exists for libfuse versions 3-3.10.1.

**Comment by mxmlnkn** [comment]
> According to [rclone/rclone#3562 (comment)](https://github.com/rclone/rclone/issues/3562#issuecomment-533813927), we might just be able to omit the "nonempty" option and it should use that behavior by default.

That's also the conclusion I came to, except, I would want to still support prior versions. So, we should test somewhow what libfuse version is being used and then decide whether to use nonempty or not?

**Comment by mxmlnkn** [comment]
Github Actions' ubuntu-latest seems to have `fusepy 3.9.0` installed but can be downgraded to a working version using `apt-get install fuse`, which removes the `fuse3` package.

[This](https://github.com/mxmlnkn/ratarmount/runs/2924444988?check_suite_focus=true) is the non-empty bug produced on ubuntu-latest. But after implementing my fix, which checks the version and omits the `nonempty` option, I [get](https://github.com/mxmlnkn/ratarmount/runs/2924964360?check_suite_focus=true):

```
==> ratarmount.stdout.log <==
Found FUSE version: [3, 9, 0]

==> ratarmount.stderr.log <==
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
Traceback (most recent call last):
  File "/home/runner/work/ratarmount/ratarmount/ratarmount.py", line 2528, in <module>
    cli(sys.argv[1:])
  File "/home/runner/work/ratarmount/ratarmount/ratarmount.py", line 2516, in cli
    fuse.FUSE(
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

This is beyond infuriating! I'm not sure whether this is an issue with fusepy or what not but it seems I'm not able to fix this right now.

**Comment by epicfaace** [comment]
Could we just downgrade ubuntu for now?

**Comment by mxmlnkn** [comment]
You already did that and it works. I just wanted to close the issue and now with fd9d53c in master I'll close this issue for now. Note that the real "fix" in there is adding `fuse` to the `apt-get install` call.
