### ISSUE TITLE
Cannot install on MacOSX due to dependency

### ISSUE THREAD

**Issue by cphyc** [mxmlnkn/ratarmount#68]
The package cannot be installed due to the following requirement
https://github.com/mxmlnkn/ratarmount/blob/f0f6ef09f3475a6099384a53040847b3f7b31aa3/requirements.txt#L4

I have created an issue upstream (https://github.com/martinellimarco/indexed_zstd/issues/2). If fixed, this should solve the issue but the version of `indexed_zstd` should be at least that of the future release. Otherwise, it may be necessary to specify the dependency is on Linux only.

**Comment by mxmlnkn** [comment]
Thank you for reporting this. I hope, this can be fixed upstream but I want to add that ratarmount is kinda defensively programmed and will even work with the compression dependencies missing, of course, it will then not support that particular compression.

So, if you want to simply install it, you can use the `--no-deps` options for pip. This is hacky, I admit but can be helpful if you cannot wait. I'm not sure how you would do the same in setuptools if you have a package which depends on ratarmount.

In the future, the dependencies might only increase and I already had problems with the FUSE dependency. So, I'm planning to split ratarmount into a core/library package and a CLI package, see also #65. Noticing this problem and many others, I'm thinking about making the compression backend dependencies for the core package optional. But, I saw your PR for yt and it seems you are depending on the FUSE mounting capabilities anyway.

This is my first Python package and I'm currently in a bit of a predicament with managing all the dependencies. Most users, especially from other Python projects might only require one or none of the supported compressions. Adding all compression backends as dependencies leads to problems like this. If you have any ideas how to basically allow those dependencies to "fail" but still install them automatically via pip if available, I'd be glad to know.

**Comment by cphyc** [comment]
Thanks for the proposed solution, I think it is safer to wait a bit for the issue to be fixed upstream.
I guess you could define your dependencies as optional rather than mandatory, using e.g. https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies?

**Comment by mxmlnkn** [comment]
The problem I have with this, is that the user would have to call `pip install ratarmount[extras]` and I'm pretty sure that most will try it without the extras first and then wonder why gzip or bz2 support is not working.

I think I'll go with the route of testing all dependencies on each platform and not make them required on unsupported platforms.

**Comment by cphyc** [comment]
That's a fair point. The only concern about manually flagging platforms is that you need to keep track of which platform is supported and which one is not, which may be cumbersome on the long run.

**Comment by mxmlnkn** [comment]
That's true. Maybe I can integrate it into the CI somehow to make it less bothersome.

**Comment by cphyc** [comment]
@mxmlnkn I have created a PR that adds testing on Windows/MacOSX (https://github.com/mxmlnkn/ratarmount/pull/69). None of the tests passes at the moment because of the aforementioned compilation issue on MacOSX, and because the workflow is kind of broken on Windows.

**Comment by mxmlnkn** [comment]
Thank you for setting up a skeleton in the CI! I do not have experience with Github Actions and Mac/Windows, so it is a huge help. I can work with this as a starting point. For now, I might wait a week or so for `indexed_zstd` to fix it and then I'll see further.

**Comment by martinellimarco** [comment]
Just to give you guys an update I'll be able to work on this during the weekend. I have access to a Mac, it shouldn't be a problem to fix this.

**Comment by martinellimarco** [comment]
Fixed in [v1.3.0](https://pypi.org/project/indexed-zstd/1.3.0/).

**Comment by martinellimarco** [comment]
I have tested ratarmount on Big Sur.

It install successfully now but there is a problem.

```
$ pip3 install ratarmount --user
Collecting ratarmount
  Using cached https://files.pythonhosted.org/packages/69/8c/b012e7ec684ce31fae29c40e6e88206d3f25b0719999585b54c4fc0af222/ratarmount-0.8.1-py3-none-any.whl
Collecting indexed-bzip2>=1.1.2 (from ratarmount)
  Using cached https://files.pythonhosted.org/packages/d5/6b/3d5ab08dd6f62affe14e3354956b184d6dd7601d578e1ad9e33440e9b579/indexed_bzip2-1.2.0.tar.gz
Collecting indexed-gzip>=1.5.3 (from ratarmount)
  Using cached https://files.pythonhosted.org/packages/0f/b0/cdc615a784235d45b75d18f8e98785e26b209264dc299d50f4d716815191/indexed_gzip-1.6.1.tar.gz
Collecting fusepy (from ratarmount)
Requirement already satisfied: indexed-zstd>=1.2.2 in /Users/imac/Library/Python/3.8/lib/python/site-packages (from ratarmount) (1.3.0)
Building wheels for collected packages: indexed-bzip2, indexed-gzip
  Building wheel for indexed-bzip2 (setup.py) ... done
  Created wheel for indexed-bzip2: filename=indexed_bzip2-1.2.0-cp38-cp38-macosx_10_14_6_x86_64.whl size=221035 sha256=80e4b953a78feb81ac08822748693c719c0a2733b294f3c1b3c3c40c641d4adf
  Stored in directory: /Users/imac/Library/Caches/pip/wheels/d6/62/cc/c734d939b5ae818bde8433e932fa5ef897f89a627e9390dc30
  Building wheel for indexed-gzip (setup.py) ... done
  Created wheel for indexed-gzip: filename=indexed_gzip-1.6.1-cp38-cp38-macosx_10_14_6_x86_64.whl size=230594 sha256=2129b1c7094c5371c68785bbb7cb20c122f82fd2ef0d188d2a94032df0f1c478
  Stored in directory: /Users/imac/Library/Caches/pip/wheels/7b/87/cc/4ef1ff2141b744a54e0c0b7ea3c5a28e72003c2bf478fdfae3
Successfully built indexed-bzip2 indexed-gzip
Installing collected packages: indexed-bzip2, indexed-gzip, fusepy, ratarmount
  WARNING: The script ratarmount is installed in '/Users/imac/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed fusepy-3.0.1 indexed-bzip2-1.2.0 indexed-gzip-1.6.1 ratarmount-0.8.1
```

However, when I try to mount anything it complains it lack libfuse

```
$ /Users/imac/Library/Python/3.8/bin/ratarmount example.tar example/
Traceback (most recent call last):
  File "/Users/imac/Library/Python/3.8/bin/ratarmount", line 6, in <module>
    from ratarmount import cli
  File "/Users/imac/Library/Python/3.8/lib/python/site-packages/ratarmount.py", line 26, in <module>
    import fuse
  File "/Users/imac/Library/Python/3.8/lib/python/site-packages/fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse
```

I tried to install libfuse with homebrew. The package is there but it requires Linux.

```
$ brew install libfuse                                     
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

libfuse: Linux is required for this software.
Error: An unsatisfied requirement failed this build.
```

I then did some research and found that libfuse for MacOS is in the package osxfuse. `brew install osxfuse` run successfully.

As soon as I tried to use the newly installed fuse MacOS asked me to reboot to complete the install.

At this point I tried again to mount a simple tar archive

```
$ /Users/imac/Library/Python/3.8/bin/ratarmount example.tar example/
/bin/sh: fusermount: command not found
Creating offset dictionary for /Users/imac/xx/example.tar ...
Creating new SQLite index database at /Users/imac/xx/example.tar.index.sqlite
Creating offset dictionary for /Users/imac/xx/example.tar took 0.00s
Writing out TAR index to /Users/imac/xx/example.tar.index.sqlite took 0s and is sized 24576 B
```

It can't find fusermount which upon further research doesn't seem to exist for MacOS.

The folder example appears to be empty but it also appear to be mounted(?).

If I run umount the first time I get nothing, like if it really did unmount the folder. The second time it complain it's not mounted, as expected.

```
$ umount example
$ umount example
umount: example: not currently mounted
```

Any idea?

**Comment by mxmlnkn** [comment]
Thanks for fixing it so soon.

My first idea would be to create a `fusermount` binary available in your `PATH` variable. That `fusermount` "binary" can be a simple link to whatever the equivalent binary is called on MacOS.

My first instinct would be to point to `fusepy`, which is pretty dead for years and has spawned some forks like `refuse`, which also seem pretty dead right now, unfortunately. But, `fusepy` states that it does indeed support Mac and I don't see any open issues mentioning Mac, so maybe it is a problem with ratarmount not implementing the FUSE API perfectly.

Maybe you seem something more interesting with: `ratarmount -d 3 -o debug ...`.

As for the usage in `yt`, personally, I think that a library-like usage would be better than going through FUSE. But I admit that there is no really stable interface to ratarmount as a library yet. It is in development, e.g., see the `develop` branch. And I have three weeks of vacation starting next week, so, I might actually release ratarmount-core 1.0.0 and ratarmount 1.0.0. The former would hopefully expose a stable interface without FUSE.

**Comment by martinellimarco** [comment]
Did some more testing. With `-o debug` it works without providing a `fusermount` replacement.

|Tested|Result|
--- | ---
|Uncompressed .tar archive|:heavy_check_mark:|
|.tar.gz archive|:heavy_check_mark:|
|.tar.zst archive|:heavy_check_mark:|
|.tar.bz2 archive|:x:|

This is the output with an example.tar.b2

```
$ /Users/imac/Library/Python/3.8/bin/ratarmount example.tar.bz2 example/ -o debug
Traceback (most recent call last):
  File "/Users/imac/Library/Python/3.8/bin/ratarmount", line 10, in <module>
    sys.exit(cli())
  File "/Users/imac/Library/Python/3.8/lib/python/site-packages/ratarmount.py", line 2666, in cli
    args = _parseArgs(rawArgs)
  File "/Users/imac/Library/Python/3.8/lib/python/site-packages/ratarmount.py", line 2624, in _parseArgs
    args.mount_source = [
  File "/Users/imac/Library/Python/3.8/lib/python/site-packages/ratarmount.py", line 2625, in <listcomp>
    TarFileType(encoding=args.encoding)(tarFile)[0] if not os.path.isdir(tarFile) else os.path.realpath(tarFile)
  File "/Users/imac/Library/Python/3.8/lib/python/site-packages/ratarmount.py", line 2355, in __call__
    raise argparse.ArgumentTypeError("Archive '{}' can't be opened!\n".format(tarFile))
argparse.ArgumentTypeError: Archive 'example.tar.bz2' can't be opened!
```

**Comment by mxmlnkn** [comment]
Interesting that it works without a fusermount replacement for you. I implemented a lot of fixes now, one of them being that ratarmount gets the fuse version from fusepy itself if it count find fusermount. It still tries fusermount first because the way I get it from fusepy does not seem to belong to the public stable interface. Then again, fusepy is not being updated all that frequently.

As for .bz2 not working on macOS, it seems there are some very weird pecularities on macOS regarding file handling. I do some tricks like opening a given python file object file by opening the fileno associated with it, which effectively opens the file a second time. The problem seems to happen if that file was already read from or seeked. It seems that the second open "inherits" the file position which leads to the unexpected effect of the file being at a non-0 file position directly after opening it. For the parallel backend, I already did some tricks like not using `dup`, which seems to not give me an independent file position (seek one and the opened dup'ed file also gets seeked). After dup did not work, I used `/proc/self/fd`, which does not exist on macOS but `/dev/fd` did. But even that did not work sufficiently (only on macOS), so now I have a `SharedFileReader` class, which opens the file only once, seeks to 0 directly after opening, and serializes file access from multiple threads through a mutex.

Now that the bzip2 decoder works with a FileReader interface as input, adding support for Python file-like objects was also relatively easy. With this, recursive mounting can be improved further :).

I'll close this for now, ratarmount `master` should work after `indexed_bzip2` 1.3.0 has been released. The ratarmount `setup.py` already expects version 1.3.0, which might not have been the best idea in hindsight. You can get around this by installing `indexed_bzip2` master before installing ratarmount master. For that reason, I'll do a new `indexed_bzip2` release in the next days after I have tested around a bit with recursive mounting.
