### ISSUE TITLE
Preserve write permissions

### ISSUE THREAD

**Issue by basos9** [mxmlnkn/ratarmount#74]
Mounting with 

```
ratarmount -P 5 mars.tar ma

$ ls -l ma
total 101
-r-------- 1 root root 12288 Οκτ   5 14:06 aquota.group
-r-------- 1 root root 10240 Οκτ   5 14:06 aquota.user
lr-xr-xr-x 1 root root     0 Ιουν 24 14:45 bin -> usr/bin
dr-xr-xr-x 1 root root     0 Νοε  12 12:22 boot
dr-xr-xr-x 1 root root     0 Νοε  12 13:10 etc

```

while the original tar

```
$ tar -tvf mars.tar  | grep ...
-rw------- root/root     12288 2021-10-05 14:06 ./aquota.group
drwxr-xr-x root/root         0 2021-11-12 12:22 ./boot/

```

I am using tar mounts to restore to system via `rsync`, so it is necessary for the original permissions to be kept. 
I have tested allow_other option to no avail.

```
$ ratarmount --version
ratarmount 0.9.1
```

**Comment by mxmlnkn** [comment]
Ratarmount has no write support therefore it felt wrong to keep write permissions. Theoretically I could allow write permissions and simply make all write/modify operations fail. I'm not sure what other similar programs do for cases like this. I'm not sure whether ratarmount is suited for your usecase with rsync. It might be better to simply do `tar xf`. It also should support only extract specified subfolders. Note that -P 5 will only speed up decompression for bz2 compressed TARs.

**Comment by basos9** [comment]
Hi and thank you for your reply. I found the tool totally fit for the purpose of reading tar.gz files without the need for extra space needed to uncompress data. And indeed it is very fast compared to archivemount.

Regarding the permissions issue, it is clear to me that preserving permissions is closer to the standard unix semantics for mounting filesystems. With the present logic one looses information (the permissions metadata) that exist on the tar archive. The feature of **read-only** mounts is also a standard mount option (**`ro`**) for most filesystems. It works by specifying a mount option that renders any write attempt erroneous. But this is irrelevant of the file's permissions. Fuse also supports this option `-o ro` so a ratarmount -o ro will suffice (As I understand,in the present implementation writes are not supported but his could be useful for the future).

As an example consider a usual filesystem mount with 'ro` read-only option.
For example mount 
```
mount | grep sdc2
/dev/sdc2 on /media/data type fuseblk (ro,...)

ls -ld /media/data
drwxrwxrwx 1 user user 4096 Νοε  18 17:02 /media/data/


touch /media/data/1
touch: cannot touch '/media/data/1': Read-only file system

````

**Comment by mxmlnkn** [comment]
Thank you for looking this up and bringing this interface inconsistency to my attention. I'm sorry for how long it took for a simple one-line fix. You can test it out with:

    python3 -m pip install --user --force-reinstall git+https://github.com/mxmlnkn/ratarmount.git@bugfixes-0.9.x#egginfo=ratarmount

I'll probably also do a 0.9.2 release today.

**Comment by basos9** [comment]
Hello
Thank you for the response. Yes this is fixed !
```
$ ratarmount -P 6 -o ro merc.tbz merc.tar/
$ ls -l merc.tar/
total 38
-rw------- 1 root root 13312 Νοε  11 17:30 aquota.group
-rw------- 1 root root 11264 Νοε  11 17:30 aquota.user
dr-xr-xr-x 1 root root     0 Οκτ   5  2019 bin
dr-xr-xr-x 1 root root     0 Ιουλ 26  2019 boot
...
```
