### ISSUE TITLE
An option to limit a recursion depth on when using -r

### ISSUE THREAD

**Issue by Vadiml1024** [mxmlnkn/ratarmount#84]
It seems that actually no way to limit the recursion depth...
In my use case it would be very useful

**Comment by mxmlnkn** [comment]
This triggers a Déjà-vu. I think, I already had a commit for this. Maybe I didn't commit and push it to the develop branch yet.

**Comment by mxmlnkn** [comment]
I added it to the develop branch: d790cbb. There is one large todo but it should already work sufficiently for the use case in #83.
