### ISSUE TITLE
Allow mounting tar subdirectory

### ISSUE THREAD

**Issue by Raviu8** [mxmlnkn/ratarmount#9]
Sometimes that tar archive itself has a topdirectory where all files resides under it.
For example: TopDir/blabla

So I want to be able to mount not root dir but TopDir/ or any other sub-directory onto the target mount point.

**Comment by mxmlnkn** [comment]
I merged the feature. Please try the `-p` option:

    python3 ratarmount.py -p TopDir/ file.tar mountpoint
    stat mountpoint/blabla
